import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: {
    width: 270,
    maxWidth: 270,
  },
  pillsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: 270,
    maxWidth: 270,
    gap: 6,
    marginBottom: 8,
  },
  inputWrapperOuter: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ccc",
    width: 270,
    maxWidth: 270,
    minHeight: 40,
  },
  inputWrapper: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    paddingLeft: 10,
    paddingVertical: 4,
    paddingRight: 4,
    gap: 4,
  },
  chevronButton: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    fontSize: 14,
    color: "#333",
    fontWeight: "500",
    minHeight: 24,
    paddingVertical: 0,
  },
  dropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ddd",
    marginTop: 4,
    maxHeight: 200,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 100,
    zIndex: 100,
  },
  dropdownItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  dropdownText: {
    fontSize: 14,
    color: "#333",
  },
})